```dockerfile
FROM python:3.9-slim
   
WORKDIR /app
 
# Установка Chrome и ChromeDriver
RUN apt-get update && apt-get install -y \
chromium \
chromium-driver
 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
 
COPY . .
  
CMD ["python", "main.py"]